default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres 
  password: postgresql 
  port: 5432

development:
  <<: *default
  database: oremeshi_development 
test:
  <<: *default
  database: oremeshi_test


production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5